import type { Vehicle } from '@/types/inventory'

export const SEED_DEALER_ID = 'obrians'

export const SEED_VEHICLES: Vehicle[] = [
  {
    id: 'obrians-001',
    dealer_id: SEED_DEALER_ID,
    vin: '1C6SRFLT7PN123456',
    stock_number: 'OBA-2301',
    year: 2023,
    make: 'RAM',
    model: '1500',
    trim: 'Sport 4x4',
    body_style: 'Crew Cab Pickup',
    mileage: 18420,
    price: 58900,
    msrp: 64200,
    status: 'available',
    images: ['/Hero-backround.jpg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Diamond Black Crystal',
    interior_color: 'Black',
    features: [
      'Remote Start',
      'Heated Front Seats',
      'Heated Steering Wheel',
      '4WD',
      'Tow Package',
      'Backup Camera',
      'Apple CarPlay / Android Auto',
      'Blind Spot Monitoring',
      'LED Headlights',
      'Sport Performance Hood',
    ],
    description:
      "Saskatchewan-ready Sport trim with the 5.7L HEMI V8. Full tow package, heated seats, and remote start for those -40 mornings. Low km, one owner, no accidents.",
    updated_at: '2026-04-01T10:00:00Z',
  },
  {
    id: 'obrians-002',
    dealer_id: SEED_DEALER_ID,
    vin: '1FTFW1E50NFB78901',
    stock_number: 'OBA-2202',
    year: 2022,
    make: 'Ford',
    model: 'F-150',
    trim: 'XLT',
    body_style: 'SuperCrew Cab',
    mileage: 34810,
    price: 51200,
    msrp: 56500,
    status: 'available',
    images: ['/Hero-backround.jpg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Iconic Silver',
    interior_color: 'Medium Dark Slate',
    features: [
      'Remote Start',
      'Heated Front Seats',
      'FordPass Connect 4G LTE',
      '4x4',
      'Class IV Trailer Hitch',
      'SYNC 4 Infotainment',
      'Ford Co-Pilot360 Assist',
      'Pro Trailer Backup Assist',
      'Box Liner',
    ],
    description:
      'Well-maintained XLT with the 3.5L EcoBoost. Clean Carfax, serviced at Ford dealer throughout. Perfect work or ranch truck.',
    updated_at: '2026-04-05T09:30:00Z',
  },
  {
    id: 'obrians-003',
    dealer_id: SEED_DEALER_ID,
    vin: '1C4RJFBG5PC234567',
    stock_number: 'OBA-2401',
    year: 2024,
    make: 'Jeep',
    model: 'Grand Cherokee',
    trim: 'Limited',
    body_style: 'SUV',
    mileage: 9200,
    price: 67400,
    msrp: 72100,
    status: 'available',
    images: ['/Hero-backround.jpg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Velvet Red Pearl',
    interior_color: 'Global Black',
    features: [
      'Remote Start',
      'Heated Front & Rear Seats',
      'Heated Steering Wheel',
      'Quadra-Trac II 4WD',
      'Panoramic Sunroof',
      'McIntosh Audio System',
      'Adaptive Cruise Control',
      'Lane Keep Assist',
      'Parallel & Perpendicular Park Assist',
      'Ventilated Front Seats',
    ],
    description:
      'Nearly new 2024 Grand Cherokee Limited. Family SUV with every comfort feature. Quadra-Trac II handles Saskatchewan winters effortlessly.',
    updated_at: '2026-04-10T14:00:00Z',
  },
  {
    id: 'obrians-004',
    dealer_id: SEED_DEALER_ID,
    vin: '3GNAXUEV5ML345678',
    stock_number: 'OBA-2104',
    year: 2021,
    make: 'Chevrolet',
    model: 'Equinox',
    trim: 'LT',
    body_style: 'SUV',
    mileage: 61350,
    price: 31800,
    msrp: undefined,
    status: 'available',
    images: ['/Hero-backround.jpg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Summit White',
    interior_color: 'Jet Black',
    features: [
      'Remote Start',
      'Heated Front Seats',
      'AWD',
      'Apple CarPlay / Android Auto',
      'Chevrolet Safety Assist',
      'Rear Vision Camera',
      'Teen Driver Technology',
      'Roof Rails',
    ],
    description:
      'Solid city and highway crossover. AWD, remote start, and heated seats — all the Saskatchewan essentials at a sharp price point.',
    updated_at: '2026-04-08T11:00:00Z',
  },
  {
    id: 'obrians-005',
    dealer_id: SEED_DEALER_ID,
    vin: '5TFFX5F16PX456789',
    stock_number: 'OBA-2305',
    year: 2023,
    make: 'Toyota',
    model: 'Tundra',
    trim: 'TRD Pro',
    body_style: 'CrewMax Pickup',
    mileage: 22760,
    price: 72100,
    msrp: 79400,
    status: 'pending',
    images: ['/Hero-backround.jpg'],
    fuel_type: 'Hybrid',
    transmission: 'Automatic',
    exterior_color: 'Lunar Rock',
    interior_color: 'Black',
    features: [
      'Remote Start',
      'Heated & Ventilated Front Seats',
      'Heated Rear Seats',
      'i-FORCE MAX Hybrid Powertrain',
      '4WD with Multi-Terrain Select',
      'TRD-Tuned Fox Shocks',
      'Skid Plates',
      'Wireless Apple CarPlay / Android Auto',
      'JBL Premium Audio',
      'Multi-Terrain Monitor',
      'Toyota Safety Sense 2.5+',
    ],
    description:
      'The TRD Pro is the ultimate off-road Tundra. Hybrid i-FORCE MAX delivers 437 hp. Fox shocks, skid plates, and Lunar Rock colour — a serious build.',
    updated_at: '2026-04-15T08:45:00Z',
  },
  {
    id: 'obrians-006',
    dealer_id: SEED_DEALER_ID,
    vin: '5NMS3DAJ0NH567890',
    stock_number: 'OBA-2206',
    year: 2022,
    make: 'Hyundai',
    model: 'Tucson',
    trim: 'Preferred',
    body_style: 'SUV',
    mileage: 47990,
    price: 34500,
    msrp: 37800,
    status: 'available',
    images: ['/Hero-backround.jpg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Phantom Black',
    interior_color: 'Black',
    features: [
      'Remote Start',
      'Heated Front Seats',
      'Heated Steering Wheel',
      'AWD',
      '10.25" Touchscreen',
      'Apple CarPlay / Android Auto',
      'Blind Spot Collision Warning',
      'Rear Cross-Traffic Collision Warning',
      'Lane Keeping Assist',
      'Smart Cruise Control',
    ],
    description:
      "Great value AWD compact SUV. Phantom Black with panoramic feel interior. Remote start and heated everything for prairie winters. Service history on file.",
    updated_at: '2026-04-12T13:15:00Z',
  },
]
