import type { Vehicle } from '@/types/inventory'

export const SEED_DEALER_ID = 'obrians'

export const SEED_VEHICLES: Vehicle[] = [
  {
    id: 'obrians-001',
    dealer_id: SEED_DEALER_ID,
    vin: '1C6SRFLT7PN123456',
    stock_number: 'OBA-2301',
    year: 2023,
    make: 'RAM',
    model: '1500',
    trim: 'Sport 4x4',
    body_style: 'Crew Cab Pickup',
    mileage: 18420,
    price: 58900,
    msrp: 64200,
    status: 'available',
    images: ['/motors/rh-coming-soon.svg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Diamond Black Crystal',
    interior_color: 'Black',
    features: [
      'Remote Start',
      'Heated Front Seats',
      'Heated Steering Wheel',
      '4WD',
      'Tow Package',
      'Backup Camera',
      'Apple CarPlay / Android Auto',
      'Blind Spot Monitoring',
      'LED Headlights',
      'Sport Performance Hood',
    ],
    description:
      "Saskatchewan-ready Sport trim with the 5.7L HEMI V8. Full tow package, heated seats, and remote start for those -40 mornings. Low km, one owner, no accidents.",
    updated_at: '2026-04-01T10:00:00Z',
  },
  {
    id: 'obrians-002',
    dealer_id: SEED_DEALER_ID,
    vin: '1FTFW1E88NFB85190',
    stock_number: '20846A',
    year: 2022,
    make: 'Ford',
    model: 'F-150',
    trim: 'XLT 4WD SuperCrew 5.5\' Box',
    body_style: 'SuperCrew Cab',
    mileage: 76393,
    price: 40998,
    msrp: undefined,
    status: 'available',
    images: ['/motors/f150-xlt-2022.jpeg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Oxford White',
    interior_color: 'Black',
    features: [
      '3.5L V6 EcoBoost Engine',
      '4x4',
      'SuperCrew Cab — 5.5\' Box',
      'Ford Co-Pilot360 Assist',
      'SYNC 4 Infotainment',
      'FordPass Connect 4G LTE',
      'Class IV Trailer Hitch',
      'Pro Trailer Backup Assist',
      'Heated Front Seats',
      'Remote Start',
      'Box Liner',
    ],
    description:
      'Oxford White SuperCrew XLT with the 3.5L V6 EcoBoost and full 4x4. Clean CARFAX, free delivery anywhere in Saskatchewan. Solid work or ranch truck at a sharp price.',
    updated_at: '2026-04-24T10:00:00Z',
  },
  {
    id: 'obrians-003',
    dealer_id: SEED_DEALER_ID,
    vin: '1C4RJFBG5PC234567',
    stock_number: 'OBA-2401',
    year: 2024,
    make: 'Jeep',
    model: 'Grand Cherokee',
    trim: 'Limited',
    body_style: 'SUV',
    mileage: 9200,
    price: 67400,
    msrp: 72100,
    status: 'available',
    images: ['/motors/rh-coming-soon.svg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Velvet Red Pearl',
    interior_color: 'Global Black',
    features: [
      'Remote Start',
      'Heated Front & Rear Seats',
      'Heated Steering Wheel',
      'Quadra-Trac II 4WD',
      'Panoramic Sunroof',
      'McIntosh Audio System',
      'Adaptive Cruise Control',
      'Lane Keep Assist',
      'Parallel & Perpendicular Park Assist',
      'Ventilated Front Seats',
    ],
    description:
      'Nearly new 2024 Grand Cherokee Limited. Family SUV with every comfort feature. Quadra-Trac II handles Saskatchewan winters effortlessly.',
    updated_at: '2026-04-10T14:00:00Z',
  },
  {
    id: 'obrians-004',
    dealer_id: SEED_DEALER_ID,
    vin: '3GNAXUEV5ML345678',
    stock_number: 'OBA-2104',
    year: 2021,
    make: 'Chevrolet',
    model: 'Equinox',
    trim: 'LT',
    body_style: 'SUV',
    mileage: 61350,
    price: 31800,
    msrp: undefined,
    status: 'available',
    images: ['/motors/rh-coming-soon.svg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Summit White',
    interior_color: 'Jet Black',
    features: [
      'Remote Start',
      'Heated Front Seats',
      'AWD',
      'Apple CarPlay / Android Auto',
      'Chevrolet Safety Assist',
      'Rear Vision Camera',
      'Teen Driver Technology',
      'Roof Rails',
    ],
    description:
      'Solid city and highway crossover. AWD, remote start, and heated seats — all the Saskatchewan essentials at a sharp price point.',
    updated_at: '2026-04-08T11:00:00Z',
  },
  {
    id: 'obrians-005',
    dealer_id: SEED_DEALER_ID,
    vin: '5TFFX5F16PX456789',
    stock_number: 'OBA-2305',
    year: 2023,
    make: 'Toyota',
    model: 'Tundra',
    trim: 'TRD Pro',
    body_style: 'CrewMax Pickup',
    mileage: 22760,
    price: 72100,
    msrp: 79400,
    status: 'pending',
    images: ['/motors/rh-coming-soon.svg'],
    fuel_type: 'Hybrid',
    transmission: 'Automatic',
    exterior_color: 'Lunar Rock',
    interior_color: 'Black',
    features: [
      'Remote Start',
      'Heated & Ventilated Front Seats',
      'Heated Rear Seats',
      'i-FORCE MAX Hybrid Powertrain',
      '4WD with Multi-Terrain Select',
      'TRD-Tuned Fox Shocks',
      'Skid Plates',
      'Wireless Apple CarPlay / Android Auto',
      'JBL Premium Audio',
      'Multi-Terrain Monitor',
      'Toyota Safety Sense 2.5+',
    ],
    description:
      'The TRD Pro is the ultimate off-road Tundra. Hybrid i-FORCE MAX delivers 437 hp. Fox shocks, skid plates, and Lunar Rock colour — a serious build.',
    updated_at: '2026-04-15T08:45:00Z',
  },
  {
    id: 'obrians-006',
    dealer_id: SEED_DEALER_ID,
    vin: '5NMS3DAJ0NH567890',
    stock_number: 'OBA-2206',
    year: 2022,
    make: 'Hyundai',
    model: 'Tucson',
    trim: 'Preferred',
    body_style: 'SUV',
    mileage: 47990,
    price: 34500,
    msrp: 37800,
    status: 'available',
    images: ['/motors/rh-coming-soon.svg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Phantom Black',
    interior_color: 'Black',
    features: [
      'Remote Start',
      'Heated Front Seats',
      'Heated Steering Wheel',
      'AWD',
      '10.25" Touchscreen',
      'Apple CarPlay / Android Auto',
      'Blind Spot Collision Warning',
      'Rear Cross-Traffic Collision Warning',
      'Lane Keeping Assist',
      'Smart Cruise Control',
    ],
    description:
      "Great value AWD compact SUV. Phantom Black with panoramic feel interior. Remote start and heated everything for prairie winters. Service history on file.",
    updated_at: '2026-04-12T13:15:00Z',
  },
  {
    id: 'obrians-007',
    dealer_id: SEED_DEALER_ID,
    vin: '2C3CDZL92NH789012',
    stock_number: 'OBA-2307',
    year: 2023,
    make: 'Dodge',
    model: 'Challenger',
    trim: 'SRT Hellcat Redeye Jailbreak Widebody',
    body_style: 'Coupe',
    mileage: 4120,
    price: 105000,
    msrp: 118400,
    status: 'available',
    images: ['/motors/rh-coming-soon.svg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Pitch Black',
    interior_color: 'Black/Sepia',
    features: [
      'Supercharged 6.2L HEMI V8 — 807 hp',
      'Jailbreak Edition',
      'Widebody Aero Package',
      'Brembo 6-Piston Brakes',
      'SRT-Tuned Adaptive Damping Suspension',
      'Launch Control',
      'Line Lock',
      'Drag Mode',
      'Performance Pages',
      'Harman Kardon Audio',
      'Heated & Ventilated Front Seats',
      'Sunroof Delete',
    ],
    description:
      "One of the last Challengers ever built. Jailbreak edition 807 hp Redeye Widebody on Pitch Black with the Sepia interior. 4,120 km — essentially new. This one won't sit.",
    updated_at: '2026-04-23T18:00:00Z',
  },
  {
    id: 'obrians-008',
    dealer_id: SEED_DEALER_ID,
    vin: '1FTEW1E81PFC00000',
    stock_number: '21065B',
    year: 2023,
    make: 'Ford',
    model: 'F-150',
    trim: 'Tremor 4WD SuperCrew 5.5\' Box',
    body_style: 'SuperCrew Cab',
    mileage: 74288,
    price: 60998,
    msrp: undefined,
    status: 'available',
    images: ['/motors/f150-tremor-2023.jpeg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Star White Metallic Tri-Coat',
    interior_color: 'Black',
    features: [
      '3.5L V6 EcoBoost Engine',
      'Tremor Off-Road Package',
      '4x4',
      'Heated Front Seats',
      'Remote Start',
      '360° Camera',
      'Reverse Camera',
      'Navigation',
      'Lane Keep Assist',
      'Cruise Control',
      'Apple CarPlay / Android Auto',
      'A/C',
    ],
    description:
      'Rare Tremor package with the 3.5L V6 EcoBoost. Star White SuperCrew with Tremor-specific off-road suspension, 360° surround camera, navigation, and heated seats. 74,288 km.',
    updated_at: '2026-04-24T10:00:00Z',
  },
  {
    id: 'obrians-009',
    dealer_id: SEED_DEALER_ID,
    vin: '2GC4YTEY6P1728043',
    stock_number: '21089A',
    year: 2023,
    make: 'Chevrolet',
    model: 'Silverado 3500HD',
    trim: 'LT 4WD Crew Cab 159"',
    body_style: 'Crew Cab Pickup',
    mileage: 52093,
    price: 60998,
    msrp: undefined,
    status: 'available',
    images: ['/motors/silverado-3500hd-2023.jpeg'],
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    exterior_color: 'Summit White',
    interior_color: 'Grey',
    features: [
      '6.6L Duramax Turbo-Diesel V8',
      '4x4',
      'Accident Free',
      'Reverse Camera',
      'Cruise Control',
      'A/C',
      'Tow Package',
    ],
    description:
      'Summit White 3500HD Crew Cab with the 6.6L Duramax Turbo-Diesel. Accident-free history, 4x4, full tow package. Built to handle any Saskatchewan load.',
    updated_at: '2026-04-24T10:00:00Z',
  },
  {
    id: 'obrians-010',
    dealer_id: SEED_DEALER_ID,
    vin: '1GKS2BKD1PR355168',
    stock_number: '21188A',
    year: 2023,
    make: 'GMC',
    model: 'Yukon',
    trim: 'SLT',
    body_style: 'SUV',
    mileage: 128305,
    price: 59950,
    msrp: undefined,
    status: 'available',
    images: ['/motors/yukon-slt-2023.jpeg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Onyx Black',
    interior_color: 'Dark Walnut/Slate',
    features: [
      '5.3L EcoTec3 V8',
      'AWD',
      'Third-Row Seating',
      'Leather Interior',
      'Heated & Ventilated Front Seats',
      'Heated Steering Wheel',
      '360° Camera',
      'Navigation',
      'Command Start',
      'Cruise Control',
      'A/C',
    ],
    description:
      'Onyx Black Yukon SLT with the 5.3L V8. Third-row seating, full leather, heated and ventilated seats, 360° camera, and navigation. Clean Saskatchewan highway machine.',
    updated_at: '2026-04-24T10:00:00Z',
  },
  {
    id: 'obrians-011',
    dealer_id: SEED_DEALER_ID,
    vin: '3TYDZ5BNXPT030244',
    stock_number: '21062A',
    year: 2023,
    make: 'Toyota',
    model: 'Tacoma',
    trim: '4x4 Double Cab Auto',
    body_style: 'Double Cab Pickup',
    mileage: 47038,
    price: 47900,
    msrp: undefined,
    status: 'available',
    images: ['/motors/tacoma-2023.jpeg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Super White',
    interior_color: 'Grey',
    features: [
      '3.5L V6 DI DOHC',
      '4x4',
      'Accident Free',
      'Manufacturer Warranty',
      'Adaptive Cruise Control',
      'Lane Keep Assist',
      'Reverse Camera',
      'A/C',
    ],
    description:
      'Super White Tacoma 4x4 Double Cab — accident-free with manufacturer warranty remaining. 3.5L V6, adaptive cruise, lane keep. Under 50k km.',
    updated_at: '2026-04-24T10:00:00Z',
  },
  {
    id: 'obrians-012',
    dealer_id: SEED_DEALER_ID,
    vin: 'JN8AZ2AC3R9500763',
    stock_number: '20907A',
    year: 2024,
    make: 'INFINITI',
    model: 'QX80',
    trim: 'LUXE 7-Passenger',
    body_style: 'SUV',
    mileage: 102661,
    price: 47400,
    msrp: undefined,
    status: 'available',
    images: ['/motors/qx80-2024.jpeg'],
    fuel_type: 'Gasoline',
    transmission: 'Automatic',
    exterior_color: 'Anthracite Gray Metallic',
    interior_color: 'Graphite',
    features: [
      '5.6L V8 Engine',
      '4WD',
      'Accident Free',
      'Third-Row Seating — 7 Passenger',
      'Leather Interior',
      'Heated Front Seats',
      '360° Camera',
      'Navigation',
      'ProPilot Assist',
      'Command Start',
      'Cruise Control',
      'Reverse Camera',
      'A/C',
    ],
    description:
      'Anthracite Gray QX80 LUXE 7-passenger — accident-free. 5.6L V8, full leather, heated seats, 360° surround camera, ProPilot Assist, and navigation. Effortless full-size luxury.',
    updated_at: '2026-04-24T10:00:00Z',
  },
]
